# Generated by Django 3.1.6 on 2021-04-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
